In [1]:
import pandas as pd
import json
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

ZomatoData = pd.read_csv('zomato.csv',encoding='ISO-8859-1')
ZomatoData = ZomatoData.drop_duplicates().reset_index(drop=True)
def RestaurantSearch(City,Cuisine,Price='MID'):
    TEMP = ZomatoData[(ZomatoData['Cuisines'].apply(lambda x: Cuisine.lower() in x.lower())) & (ZomatoData['City'].apply(lambda x: City.lower() in x.lower()))]
    if Price.lower()=='mid':    
        TEMP=TEMP.loc[(TEMP['Average Cost for two']>= 300)&(TEMP['Average Cost for two']<= 700)].sort_values(by='Aggregate rating',ascending=False)
    if Price.lower()=='low':
        TEMP=TEMP.loc[TEMP['Average Cost for two']<300].sort_values(by='Aggregate rating',ascending=False)
    if Price.lower()=='high':
        TEMP=TEMP.loc[TEMP['Average Cost for two']>700].sort_values(by='Aggregate rating',ascending=False)
    return TEMP[['Restaurant Name','Address','Average Cost for two','Aggregate rating']].head(10)

In [109]:
RestaurantSearch('Mumbai','chinese','High')

,Restaurant Name,Address,Average Cost for two,Aggregate rating
2286,The Fusion Kitchen,"Shop 1, Opposite Veda Building, Near Bhavdevi ...",1000,4.7
2281,Yauatcha,"Raheja Tower, Bandra Kurla Complex, Mumbai",2800,4.6
2283,Butterfly High,"Unit 4, Ground Floor, Jet Airways, Godrej G Bl...",1500,4.3
2282,BKC DIVE,"Ground Floor, Pinnacle Corporate Park, Opposit...",1100,4.2
2288,Bayview Cafe,"Hotel Harbour View, Kerawala Chamber, Opposite...",1200,4.2
2291,Tea Villa Cafe,"31, Opposite Globus, Hill Road, Bandra West",1000,4.1
2316,Tea Villa Cafe,"28, Aaram Nagar 1, Opposite Dariya Mahal, Vers...",1000,4.1
2315,By The Bae - Kitchen And Bar,"9A - 9B, Aram Nagar 2, JP Road, Versova, Andhe...",2500,4.0
2304,Tea Villa Cafe,"Shop 1& 2, Y-Building, Flower Valley, Opposite...",1000,3.9
2299,Mumbai Vibe,"Ganga Jamuna Block, 14th Road, Linking Road, B...",1000,3.8

In [4]:
import smtplib 
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
def email_1(email):
        res=RestaurantSearch('hyderabad','chinese','High')
        if email == None:
            email = 'pgdmlupgrad@gmail.com'
        msg = MIMEMultipart()
        msg['Subject'] = "Your Subject"
        msg['From'] = 'pgdmlupgrad@gmail.com'
        html = """\
        <html>
          <head></head>
          <body>
            {0}
          </body>
        </html>
        """.format(res.to_html())
        part1 = MIMEText(html, 'html')
        msg.attach(part1)
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login("pgdmlupgrad@gmail.com", "pgdml@1960")
        server.sendmail(msg['From'], email , msg.as_string())

In [5]:
email_1('pgdmlupgrad@gmail.com')